### ISSUE TITLE
tools/main.js missing

### ISSUE THREAD

**Issue by idbill** [strikeout/mylar#7]
When running meteor from any location I get the following error:
$ ../meteor
Building enc_modules/crypto_mk
perl mergedep.pl obj/.deps obj/util/util.d obj/main/ec.d obj/main/multikey_sum.d obj/main/b64_wrapper.d obj/main/multikey.d obj/main/base64.d obj/main/prng.d obj/test/test.d
make: Nothing to be done for `all'.
Building enc_modules/crypto_server
make: Nothing to be done for `all'.
2926
Crypto server already running

module.js:340
    throw err;
          ^
Error: Cannot find module '/home/idbill/Workspace/mylar/tools/main.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

Note that the tools directory that is specified above does not exist.

If I do a 'find' for main.js, it shows up in:
./enc_modules/idp-pw/client/main.js
./packages/cprogress/lib/main.js
./dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/* (67 matches)

**Comment by strikeout** [comment]
Please use your "normal" `meteor` to run your project as usual. Just put everything in the `/packages` directory into your projects packages directory. The `meteor` included here was responsible for starting the crytpo-servers enabling search over enc. documents but thats an untested thingy for now...
